import type { IssuePageConfig } from "./IssuePage";

export const ISSUE_PAGE_CONFIGS = [

  {
    slug: "health",
    title: "Health",
    description:
      "Track Washington health policy: bills, hearings, testimony, and the organizations behind them — covering health care access, insurance, behavioral health, hospitals, long-term care, and Medicaid.",
    emptyLabel: "health",
    keywords: [
      "health",
      "health care",
      "healthcare",
      "public health",
      "hospital",
      "hospitals",
      "insurance",
      "medicaid",
      "behavioral health",
      "mental health",
      "substance use",
      "long-term care",
      "nursing",
      "provider",
      "providers",
      "prescription drugs",
      "pharmacy",
      "reproductive health",
      "department of health",
      "doh",
      "health care authority",
      "hca",
      "dshs",
    ],
  },
  {
    slug: "housing",
    title: "Housing",
    description:
      "Track Washington housing policy: bills, hearings, testimony, and the organizations behind them — covering zoning, permitting, affordability, and homelessness.",
    emptyLabel: "housing",
    keywords: [
      "housing",
      "zoning",
      "rent",
      "tenant",
      "homelessness",
      "affordable housing",
      "transit-oriented development",
      "permitting",
      "land use",
      "common interest communities",
      "unit owner",
    ],
  },


  {
    slug: "climate",
    title: "Climate",
    description:
      "Track Washington climate policy: bills, hearings, testimony, and the organizations behind them — covering emissions, clean energy, environmental justice, climate resilience, and carbon markets.",
    emptyLabel: "climate",
    keywords: [
      "climate",
      "emissions",
      "greenhouse gas",
      "clean energy",
      "renewable",
      "carbon",
      "cap-and-invest",
      "climate commitment act",
      "environmental justice",
      "resilience",
      "wildfire",
      "drought",
      "ev",
      "electric vehicle",
      "energy efficiency",
    ],
  },
  {
    slug: "education",
    title: "Education",
    description:
      "Track Washington education policy: bills, hearings, testimony, and the organizations behind them — covering K-12, higher education, school funding, special education, and early learning.",
    emptyLabel: "education",
    keywords: [
      "education",
      "school",
      "schools",
      "student",
      "students",
      "teacher",
      "teachers",
      "superintendent",
      "ospi",
      "higher education",
      "university",
      "college",
      "community college",
      "special education",
      "early learning",
      "childcare",
      "child care",
      "school funding",
    ],
  },

  {
    slug: "public-safety",
    title: "Public Safety",
    description:
      "Track Washington public safety policy: bills, hearings, testimony, and the organizations behind them — covering policing, courts, corrections, emergency response, and violence prevention.",
    emptyLabel: "public-safety",
    keywords: [
      "public safety",
      "police",
      "policing",
      "law enforcement",
      "criminal justice",
      "courts",
      "jail",
      "prison",
      "corrections",
      "firearm",
      "gun violence",
      "emergency management",
      "fire",
      "ems",
      "911",
      "sentencing",
      "juvenile justice",
      "domestic violence",
      "victim services",
    ],
  },
  {
    slug: "transportation",
    title: "Transportation",
    description:
      "Track Washington transportation policy: bills, hearings, testimony, and the organizations behind them — covering transit, roads, ferries, traffic safety, and infrastructure projects.",
    emptyLabel: "transportation",
    keywords: [
      "transportation",
      "transit",
      "rail",
      "bus",
      "ferry",
      "ferries",
      "highway",
      "road",
      "roads",
      "bridge",
      "bridges",
      "traffic safety",
      "wsdot",
      "sound transit",
      "public transportation",
      "vehicle miles traveled",
      "pedestrian",
      "bicycle safety",
    ],
  },
] satisfies IssuePageConfig[];

export function issuePageConfig(slug: string): IssuePageConfig | undefined {
  return ISSUE_PAGE_CONFIGS.find((issue) => issue.slug === slug);
}
