import type { IssuePageConfig } from "./IssuePage";

export const ISSUE_PAGE_CONFIGS = [

  {
    slug: "health",
    title: "Health",
    description:
      "A first issue-level view over Washington health legislation, hearings, testimony, organizations, and source records. Over time this becomes the entry point for public health, health care access, insurance, behavioral health, hospitals, long-term care, workforce, Medicaid, and health accountability data.",
    emptyLabel: "health",
    keywords: [
      "health",
      "health care",
      "healthcare",
      "public health",
      "hospital",
      "hospitals",
      "insurance",
      "medicaid",
      "behavioral health",
      "mental health",
      "substance use",
      "long-term care",
      "nursing",
      "provider",
      "providers",
      "prescription drugs",
      "pharmacy",
      "reproductive health",
      "department of health",
      "doh",
      "health care authority",
      "hca",
      "dshs",
    ],
  },
  {
    slug: "housing",
    title: "Housing",
    description:
      "A first issue-level view over Washington housing legislation, testimony, transcript excerpts, organizations, and source records. As coverage expands, this page becomes the entry point for housing bills, hearings, permitting, affordability, and accountability data.",
    emptyLabel: "housing",
    keywords: [
      "housing",
      "zoning",
      "rent",
      "tenant",
      "homelessness",
      "affordable housing",
      "transit-oriented development",
      "permitting",
      "land use",
      "common interest communities",
      "unit owner",
    ],
  },


  {
    slug: "climate",
    title: "Climate",
    description:
      "A first issue-level view over Washington climate legislation, hearings, testimony, organizations, and source records. Over time this becomes the entry point for emissions, clean energy, environmental justice, climate resilience, carbon markets, and agency accountability data.",
    emptyLabel: "climate",
    keywords: [
      "climate",
      "emissions",
      "greenhouse gas",
      "clean energy",
      "renewable",
      "carbon",
      "cap-and-invest",
      "climate commitment act",
      "environmental justice",
      "resilience",
      "wildfire",
      "drought",
      "ev",
      "electric vehicle",
      "energy efficiency",
    ],
  },
  {
    slug: "education",
    title: "Education",
    description:
      "A first issue-level view over Washington education legislation, hearings, testimony, organizations, and source records. Over time this becomes the entry point for K-12, higher education, school funding, student outcomes, workforce pathways, and education accountability data.",
    emptyLabel: "education",
    keywords: [
      "education",
      "school",
      "schools",
      "student",
      "students",
      "teacher",
      "teachers",
      "superintendent",
      "ospi",
      "higher education",
      "university",
      "college",
      "community college",
      "special education",
      "early learning",
      "childcare",
      "child care",
      "school funding",
    ],
  },
  {
    slug: "transportation",
    title: "Transportation",
    description:
      "A first issue-level view over Washington transportation legislation, hearings, testimony, organizations, and source records. Over time this becomes the entry point for transit, roads, ferries, safety, infrastructure projects, emissions, and transportation accountability data.",
    emptyLabel: "transportation",
    keywords: [
      "transportation",
      "transit",
      "rail",
      "bus",
      "ferry",
      "ferries",
      "highway",
      "road",
      "roads",
      "bridge",
      "bridges",
      "traffic safety",
      "wsdot",
      "sound transit",
      "public transportation",
      "vehicle miles traveled",
      "pedestrian",
      "bicycle safety",
    ],
  },
] satisfies IssuePageConfig[];

export function issuePageConfig(slug: string): IssuePageConfig | undefined {
  return ISSUE_PAGE_CONFIGS.find((issue) => issue.slug === slug);
}
